worker_processes auto;

events {
    worker_connections 512;
}

http {
    include mime.types;
    charset utf-8;
    source_charset utf-8;

    log_format upstreamlog '$server_name to: $upstream_addr {$request} '
   'upstream_response_time $upstream_response_time'
   ' request_time $request_time';

    server {
        listen       80;
        listen       443 ssl http2;
        listen       443 quic reuseport;
        server_name localhost;
        root /;

        access_log /var/log/nginx/nginx-access.log upstreamlog;

        ssl_certificate      /usr/nginx.crt;
        ssl_certificate_key  /usr/nginx.key;

        ssl_ciphers  HIGH:!aNULL:!MD5;
        ssl_prefer_server_ciphers on;
        ssl_protocols TLSv1.3;

        quic_gso on;
        ssl_early_data on;
        quic_retry on;
        ssl_stapling        on;
        ssl_stapling_verify on;
        add_header Alt-Svc 'h3=":443"; ma=86400';

        gzip on;
        gzip_types text/plain application/json;

        proxy_cache_methods GET;

        more_set_headers "Server: Online Bank";

        location / {
            root /usr/static;
        }

        location = /test {
            try_files /usr/static/index.html = 404;
        }

        location = /status {
            stub_status;
        }

        location = /documentation {
            try_files /usr/README.md = 404;
        }

        location = /admin {
            return 301 http://localhost:13000/signin;
        }

        location = /api {
            proxy_no_cache 1;
            proxy_cache_bypass 1;

            rewrite ^/api$ / break;
            proxy_pass https://backend-1:5001/;
        }

        location ~ ^/api/(.*?)$ {
            proxy_no_cache 1;
            proxy_cache_bypass 1;

            proxy_pass https://backend-1:5001/$1;
        }
    }
}
